[general]
import = ["./themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_timeout = 0
blink_interval = 500

[font]
normal = { family = "CaskaydiaCove Nerd Font Propo", style = "Regular" }
size = 14

[colors]
cursor = { text = "#ffc600", cursor = "#ffc600" }
draw_bold_text_with_bright_colors = true

[terminal]
# shell = { program = "/home/boradeni/.cargo/bin/fish" }
shell = { program = "/bin/bash" }
