theme = "mytheme"

[editor]
color-modes = true
cursorline = true
true-color = true
rulers = [80]
# end-of-line-diagnostics = "hint"
line-number = "relative"
insert-final-newline = false
# bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
character = "|"
render = true

[editor.lsp]
# display-messages = true
display-progress-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control", "file-name"]
# center = ["file-name"]
right = [
  "diagnostics",
  "selections",
  "position-percentage",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]

[keys.insert]
j = { f = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
# A-x = "extend_to_line_bounds"
# C-p = "file_picker"
# "C-f" = "file_picker_in_current_buffer_directory"
# C = { S = { p = "command_palette" }}
"?" = "command_palette"
G = ["goto_last_line"]
"A-r" = ":reload"
"C-d" = ["half_page_down", "goto_window_center"]
"C-u" = ["half_page_up", "goto_window_center"]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
t = ["extend_till_char", "normal_mode", "collapse_selection"]
A-w = "move_next_sub_word_start"
A-b = "move_prev_sub_word_start"
A-e = "move_next_sub_word_end"
V = ["select_mode", "extend_line_below", "extend_to_line_bounds"]
A-v = ["select_mode", "select_line_above"]
x = "delete_selection"
X = "delete_char_backward"
C = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
  "insert_mode",
]
D = [
  "extend_to_line_end",
  "yank_main_selection_to_clipboard",
  "delete_selection",
]
0 = "goto_line_start"
L = "goto_line_end"
"$" = "goto_line_end"
H = "goto_first_nonwhitespace"
"^" = "goto_first_nonwhitespace"

[keys.select]
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
V = ["extend_line_below", "extend_to_line_bounds"]
A-v = ["select_line_above"]
0 = "goto_line_start"
"$" = "goto_line_end"
H = "goto_first_nonwhitespace"
L = "goto_line_end"
"^" = "goto_first_nonwhitespace"
";" = "normal_mode"

[keys.normal.space]
"q" = ":buffer-close"
"v" = ":reload-all"
"i" = ":toggle-option lsp.display-inlay-hints"
F = "file_picker_in_current_buffer_directory"
