notARepository: 'quit'
os:
  editPreset: hx
gui:
  showBottomLine: false
  # theme:
  #   activeBorderColor:
  #     - magenta
  #   selectedLineBgColor:
  #     - black
  #   selectedRangeBgColor:
  #     - black
  #   unstagedChangesColor:
  #     - yellow
  border: rounded
  nerdFontsVersion: '3'