theme = "catppuccin_mocha"

[editor]
color-modes = true
cursorline = true
true-color = true
rulers = [80]
# end-of-line-diagnostics = "hint"
line-number = "relative" 
insert-final-newline = false
# bufferline = "multiple"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.indent-guides]
character = "|"
render = true

[editor.lsp]
# display-messages = true
display-progress-messages = true

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control", "file-name"]
# center = ["file-name"]
right = ["diagnostics", "selections", "position-percentage", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.insert]
j = { f = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
# A-x = "extend_to_line_bounds"
X = "select_line_above"


[keys.select]
# A-x = "extend_to_line_bounds"
X = "select_line_above"
# j = { f = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal.space]
"q" = ":buffer-close"
"v" = ":reload-all"
"i" = ":toggle-option lsp.display-inlay-hints"
